hw_info:
  cpu_id: ""
  cpu_name: e902
  vendor_name: ""
  chip_name: ""
  board_name: ""
  ld_script: ../board/gcc_flash.ld
  flash_program: ""
def_config:
  CONFIG_ARCH_INTERRUPTSTACK: 2048
  CONFIG_DEBUG_MODE: 1
  CONFIG_IRQ_LOOKUP: 1
  CONFIG_KERNEL_NONE: 1
  CONFIG_SUPPORT_TSPEND: 1
  CONFIG_XIP: 1
  DBG_PRINT2PC: 1
name: Demo
version: v1.2.0
description: 我的第一个方案工程
tag: ""
keywords: 
author:
  name: ""
license: ""
type: solution
depends:
  - apt32f103x_demo: v1.2.0
  - sdk_103x: v1.2.0
build_config:
  include:
    - include
    - ./
  internal_include: 
  cflag: -O0  -g  -Wall  -ffunction-sections  -fdata-sections
  cxxflag: -O0  -g  -Wall  -ffunction-sections  -fdata-sections
  asmflag: -Wa,--gdwarf2
  define: 
  libs: 
  libpath: 
source_file:
  - src/*.c
depends_forward:
  - apt32f103x_demo: v1.2.0
  - sdk_103x: v1.2.0
install: 
homepage: 